#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /home/chinchilly/ravencore/home \
			--quiet --gecos "chinchilly ravencore" ravencore
		chown -R ravencore /home/chinchilly/ravencore/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
