#! /bin/sh -e

case "$1" in
	install|upgrade)
		echo '# installed by ravencore package' > /etc/apt/sources.list.d/ravencore-nodesource.list
		echo 'deb https://deb.nodesource.com/node_10.x xenial main' >> /etc/apt/sources.list.d/ravencore-nodesource.list
		curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
		echo 'deb http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu xenial main' >> /etc/apt/sources.list.d/nodesource.list
		apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8842CE5E
		echo 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse' >> /etc/apt/sources.list.d/nodesource.list
		apt-key adv --keyserver keyserver.ubuntu.com --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
		;;
	abort-upgrade)
	;;
	*)
	    echo "preinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac

exit 0
