#!/bin/bash -e

INSTALL_PATH="/opt/underdarkskies/ravencore-rvn/"
BIN=$(realpath "$INSTALL_PATH"/ravencore/node_modules/ravencore-node/bin/ravencoin-*/bin/)
DATA="$INSTALL_PATH/home/.ravencore/data"
CONF="$DATA/raven.conf"

exec "$BIN"/raven-cli --conf="$CONF" --datadir="$DATA" "$@"
