#! /bin/sh -e

case "$1" in
	configure)
		adduser --system --home /opt/underdarkskies/ravencore-rvn/home \
			--quiet --gecos "underdarkskies ravencore-rvn" ravencore-rvn
		chown -R ravencore-rvn /opt/underdarkskies/ravencore-rvn/home
		;;
	abort-upgrade|abort-remove|abort-deconfigure)
	;;
	
	*)
	    echo "postinst called with unknown argument \`$1'" >&2
	    exit 1
	;;
esac


#DEBHELPER#

exit 0
